### PR TITLE
Make packageable.

### PR DESCRIPTION
**Pull request by simpoir**
* rename modules to be importable
* define entry points
* use pkg_resources for accessing package resources

This should allow simple distro packaging (e.g. with debhelpers),
running from any folder (instead of in the script folder),
running as zipped egg (if someone is ever into that),
or installing with just 'python3 setup.py install --user'.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Thank you! I'll take a closer as soon as my system is usable again. New SSD drive just arrived and temporarily I only have a Chromebook, until I set up Arch from scratch.

**Comment by nwg-piotr** [comment]
What worries me is that the Arch package now depends on `python-enum-compat`, which is only available in AUR. 

```
from pkg_resources import load_entry_point
```

Isn't it going to be a problem in other distributions?

**Comment by simpoir** [comment]
AFAIK python-enum-compat shouldn't be required unless you want to support older python interpreters (setup requires python >= 3.4).
pkg_resources is part of setuptools (which was already imported in setup.py). If you can install the package, that dependency is already met.

**Comment by nwg-piotr** [comment]
~~Running the command results in this:~~

```
$ sgtk-menu
Traceback (most recent call last):
  File "/usr/bin/sgtk-menu", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum-compat' distribution was not found and is required by i3ipc
```

**Comment by nwg-piotr** [comment]
Well, never mind. I tried to get rid of the `i3ipc` module, which seemed to be responsible for the issue, and probably I succeeded. The 0.10.0 pre-release (built out of the "development" branch) works well for me w/o `i3ipc` and `enum-compat`. Needs more testing, however.

**Pull request merged**
